"""
Histogram-based rank normalization for image score data using a cumulative mass function (CMF).

This algorithm normalizes image scores (generated by a previous classifier step) through a two-pass, histogram-based rank normalization process. Instead of spline interpolation, this approach directly computes the cumulative mass function (CMF) from the histogram and applies an inverse normal cumulative distribution function (CDF) for efficient normalization.

### 1. First Pass: Histogram Generation

For each image:
- Load raw image scores and the corresponding threshold image.
- Identify foreground pixels using a thresholding method (e.g., GaussianBlur).
- For each foreground pixel:
  - Scale the raw score values by a factor (e.g., 10,000) and round to the nearest integer to discretize them into histogram bins.
  - Count occurrences of each bin across all foreground pixels, constructing a global histogram.

### 2. CMF-Based Lookup Table (LUT) Generation

- Compute the **cumulative mass function (CMF)** for the histogram:
  - Sum all bin counts up to the current bin, adding half the count of the current bin.
  - Normalize by the total number of foreground pixels to obtain percentile ranks.
- Apply the inverse normal CDF (quantile function) to the CMF to create a **lookup table (LUT)** that maps raw score bins to normalized values.

### 3. Second Pass: Application of CMF LUT to Normalize Images

- Reload image scores and apply the CMF-generated LUT to each foreground pixel.
- Produce normalized final scores and save them as Zarr files.

### Advantages of CMF-Based Normalization

- **Efficiency:** Avoids the need for spline interpolation, reducing computational overhead.
- **Scalability:** Fully vectorized computation enables higher resolution histograms with more bins.
- **Stability:** Ensures smooth normalization even in cases of sparse or noisy histograms.

This method provides an efficient transformation of raw pixel scores into a normalized distribution suitable for statistical analysis and visualization.
"""
import os
import numpy as np
import zarr
import cv2
import scipy.stats
from typing import Tuple, Optional


def build_histograms_and_threshold(
    score_dir: str,
    image_dir: str,
    thresh_method: str = "GaussianBlur",
    thresh_param: int = 200,
    n_bins: int = 200_000,
    multiply_factor: int = 10_000
) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """
    First pass: build histograms from foreground pixels across all images.

    :param score_dir: Directory containing input .zarr score files.
    :param image_dir: Directory with corresponding images for thresholding.
    :param thresh_method: Thresholding method (currently supports only 'GaussianBlur').
    :param thresh_param: Threshold parameter value (e.g., pixel intensity limit).
    :param n_bins: Number of bins to use in the histogram.
    :param multiply_factor: Factor for converting scores to bin indices (e.g., 10,000).

    :return: A tuple of three histograms (one per channel) of shape (n_bins,).
    """
    # Allocate global histograms (one for each channel)
    hist_ch0 = np.zeros(n_bins, dtype=np.uint64)
    hist_ch1 = np.zeros(n_bins, dtype=np.uint64)
    hist_ch2 = np.zeros(n_bins, dtype=np.uint64)

    # Gather .zarr files and image files in a matched, sorted order
    score_mask_zarrs = sorted(f for f in os.listdir(score_dir) if f.endswith(".zarr"))
    images = sorted(os.listdir(image_dir))

    # Loop over each zarr + image pair
    for i, zarr_file in enumerate(score_mask_zarrs):
        print(f"[1/2] Building histogram from: {zarr_file} ({i+1}/{len(score_mask_zarrs)})")

        # Load the score zarr
        zm = zarr.open(os.path.join(score_dir, zarr_file))
        # Typically shape (H, W, 3, patches) => flatten channels to 1D
        ch0 = zm[:, :, 0, :].reshape(-1)
        ch1 = zm[:, :, 1, :].reshape(-1)
        ch2 = zm[:, :, 2, :].reshape(-1)

        # Load corresponding image for thresholding
        img_path = os.path.join(image_dir, images[i])
        image = cv2.imread(img_path)
        if image is None:
            raise FileNotFoundError(f"Unable to load image: {img_path}")

        # If threshold_method == "GaussianBlur", blur and use green channel
        if thresh_method == "GaussianBlur":
            # Optionally, pad the image if smaller than the zarr shape
            H, W, _ = image.shape
            ZH, ZW = zm.shape[0], zm.shape[1]
            if H < ZH:
                pad = np.ones((ZH - H, W, 3), np.uint8) * 255
                image = np.vstack((image, pad))
            if W < ZW:
                pad = np.ones((image.shape[0], ZW - W, 3), np.uint8) * 255
                image = np.hstack((image, pad))

            image = cv2.GaussianBlur(image, (9, 9), 0)
            green_channel = image[:, :, 1].reshape(-1)
            # Foreground mask
            foreground = green_channel <= thresh_param
        else:
            raise NotImplementedError(f"Threshold method '{thresh_method}' not implemented.")

        # Bin foreground pixel values
        ch0_fg = ch0[foreground]
        ch1_fg = ch1[foreground]
        ch2_fg = ch2[foreground]

        bin_idx_0 = np.clip(np.round(ch0_fg * multiply_factor).astype(int), 0, n_bins - 1)
        bin_idx_1 = np.clip(np.round(ch1_fg * multiply_factor).astype(int), 0, n_bins - 1)
        bin_idx_2 = np.clip(np.round(ch2_fg * multiply_factor).astype(int), 0, n_bins - 1)

        # Increment global histograms
        np.add.at(hist_ch0, bin_idx_0, 1)
        np.add.at(hist_ch1, bin_idx_1, 1)
        np.add.at(hist_ch2, bin_idx_2, 1)

    return hist_ch0, hist_ch1, hist_ch2


def create_cmf_lut_from_histogram(
    hist: np.ndarray,
    dist: Optional[scipy.stats.rv_continuous] = scipy.stats.norm
) -> np.ndarray:
    """
    Create a lookup table (LUT) directly from a histogram by computing the cumulative mass function (CMF)
    and applying the inverse CDF (ppf) in a vectorized fashion.
    
    The CMF is computed as:
        (sum of counts before the current bin + 0.5 * current bin count) / total counts
    This gives the mid-point probability for each bin.
    
    :param hist: 1D histogram array of bin counts.
    :param dist: A continuous distribution with a .ppf() method (default: standard normal).
    :return: A 1D LUT array of the same length as 'hist'. LUT[i] gives the normalized value for bin i.
    """
    total = hist.sum()
    if total <= 0:
        # Edge case: no data => return zeros
        return np.zeros_like(hist, dtype=np.float32)

    # Compute cumulative sum excluding the current bin
    cs = np.concatenate(([0], np.cumsum(hist[:-1])))
    # Compute the CMF: add half the count of the current bin, then divide by total count.
    cmf = (cs + hist * 0.5) / total
    # Clamp values to avoid extreme values (0 or 1) causing issues with ppf.
    cmf = np.clip(cmf, 1e-9, 1 - 1e-9)
    
    # Compute the LUT using the vectorized inverse CDF (ppf).
    lut = dist.ppf(cmf)
    return lut.astype(np.float32)


def apply_cmf_histogram_lut(
    score_dir: str,
    output_dir: str,
    image_dir: str,
    lut0: np.ndarray,
    lut1: np.ndarray,
    lut2: np.ndarray,
    multiply_factor: int = 10000,
    thresh_method: str = "GaussianBlur",
    thresh_param: int = 200
) -> None:
    """
    Second pass: Apply the cmf LUT to foreground pixels in each .zarr file, write out final scores.

    :param score_dir: Path of the input .zarr files with raw scores.
    :param output_dir: Directory where normalized .zarr files are saved.
    :param image_dir: Directory containing images used for thresholding.
    :param lut0: LUT for channel 0 (shape == (#bins,)).
    :param lut1: LUT for channel 1.
    :param lut2: LUT for channel 2.
    :param multiply_factor: Factor used to bin raw score values.
    :param thresh_method: Threshold method (default 'GaussianBlur').
    :param thresh_param: Threshold parameter (e.g., intensity limit).

    :return: None
    """
    os.makedirs(output_dir, exist_ok=True)
    score_mask_zarrs = sorted(f for f in os.listdir(score_dir) if f.endswith(".zarr"))
    images = sorted(os.listdir(image_dir))

    for i, zarr_file in enumerate(score_mask_zarrs):
        print(f"[2/2] Applying LUT to: {zarr_file} ({i+1}/{len(score_mask_zarrs)})")
        zm = zarr.open(os.path.join(score_dir, zarr_file))
        
        # Handle both 4D and 3D Zarr files.
        if len(zm.shape) == 4:
            # Expect shape (H, W, 3, patches)
            ch0 = zm[:, :, 0, :].reshape(-1)
            ch1 = zm[:, :, 1, :].reshape(-1)
            ch2 = zm[:, :, 2, :].reshape(-1)
        elif len(zm.shape) == 3:
            # Expect shape (H, W, 1)
            ch0 = zm[:, :, 0].flatten()
            ch1 = ch0.copy()
            ch2 = ch0.copy()
        else:
            raise ValueError(f"Unexpected Zarr shape: {zm.shape}")

        # Load the corresponding image and compute foreground mask.
        img_path = os.path.join(image_dir, images[i])
        image = cv2.imread(img_path)
        if image is None:
            raise FileNotFoundError(f"Unable to load image: {img_path}")

        if thresh_method == "GaussianBlur":
            H_img, W_img, _ = image.shape
            ZH, ZW = zm.shape[0], zm.shape[1]
            if H_img < ZH:
                pad = np.ones((ZH - H_img, W_img, 3), np.uint8) * 255
                image = np.vstack((image, pad))
            if W_img < ZW:
                pad = np.ones((image.shape[0], ZW - W_img, 3), np.uint8) * 255
                image = np.hstack((image, pad))
            image = cv2.GaussianBlur(image, (9, 9), 0)
            green_channel = image[:, :, 1].reshape(-1)
            foreground = green_channel <= thresh_param
        else:
            raise NotImplementedError(f"Threshold method '{thresh_method}' not implemented.")

        # Prepare output arrays for each channel.
        out_ch0 = np.zeros_like(ch0, dtype=np.float32)
        out_ch1 = np.zeros_like(ch1, dtype=np.float32)
        out_ch2 = np.zeros_like(ch2, dtype=np.float32)

        fg_ch0 = np.clip(np.round(ch0[foreground] * multiply_factor).astype(int), 0, len(lut0) - 1)
        fg_ch1 = np.clip(np.round(ch1[foreground] * multiply_factor).astype(int), 0, len(lut1) - 1)
        fg_ch2 = np.clip(np.round(ch2[foreground] * multiply_factor).astype(int), 0, len(lut2) - 1)

        out_ch0[foreground] = lut0[fg_ch0]
        out_ch1[foreground] = lut1[fg_ch1]
        out_ch2[foreground] = lut2[fg_ch2]

        # Compute the final age score by averaging channels.
        flat_age_scores = (out_ch0 + out_ch1 + out_ch2) / 3.0

        # Determine the output shape: if input is 4D (H, W, 3, patches) then output becomes (H, W, 1, patches);
        # if input is 3D (H, W, 1), then output remains (H, W, 1).
        if len(zm.shape) == 4:
            out_shape = (zm.shape[0], zm.shape[1], 1, zm.shape[3])
        elif len(zm.shape) == 3:
            out_shape = (zm.shape[0], zm.shape[1], 1)
        else:
            raise ValueError(f"Unexpected Zarr shape: {zm.shape}")

        try:
            sub_age_scores = flat_age_scores.reshape(out_shape)
        except ValueError as ve:
            raise ValueError(f"Reshape failed for file {zarr_file} with new_shape {out_shape}: {ve}")

        out_filename = zarr_file.replace(".zarr", "_age_scores.zarr")
        out_path = os.path.join(output_dir, out_filename)
        zarr.save(out_path, sub_age_scores)


def combined_age_score_cmf(
    score_dir: str,
    combined_score_dir: str,
    image_dir: str,
    thresh_method: str = "GaussianBlur",
    thresh_param: int = 200,
    dist: Optional[scipy.stats.rv_continuous] = scipy.stats.norm,
    multiply_factor: int = 10000,
    n_bins: int = 200000
) -> None:
    """
    Main entry point for cmf-based histogram rank normalization.

    1) Build global histograms for each channel from all .zarr files (foreground pixels).
    2) Generate a cmf-based LUT mapping bin -> rank -> dist.ppf(rank).
    3) Re-open each .zarr file, map foreground pixel scores through the LUT, save results.

    :param score_dir: Path to .zarr score files.
    :param combined_score_dir: Output directory for normalized .zarr files.
    :param image_dir: Path to corresponding threshold images.
    :param thresh_method: Threshold method ('GaussianBlur' only in this example).
    :param thresh_param: Threshold parameter value.
    :param dist: Distribution object with a .ppf() method (e.g., scipy.stats.norm).
    :param multiply_factor: Scale factor for converting scores to bin indices.
    :param n_bins: Number of bins for histograms.
    :return: None
    """
    # --- PASS 1: build histograms ---
    hist_ch0, hist_ch1, hist_ch2 = build_histograms_and_threshold(
        score_dir=score_dir,
        image_dir=image_dir,
        thresh_method=thresh_method,
        thresh_param=thresh_param,
        n_bins=n_bins,
        multiply_factor=multiply_factor
    )

    # --- Create spline LUT from each histogram ---
    lut0 = create_cmf_lut_from_histogram(hist_ch0, dist=dist)
    lut1 = create_cmf_lut_from_histogram(hist_ch1, dist=dist)
    lut2 = create_cmf_lut_from_histogram(hist_ch2, dist=dist)

    # --- PASS 2: apply LUT + save outputs ---
    apply_cmf_histogram_lut(
        score_dir=score_dir,
        output_dir=combined_score_dir,
        image_dir=image_dir,
        lut0=lut0,
        lut1=lut1,
        lut2=lut2,
        multiply_factor=multiply_factor,
        thresh_method=thresh_method,
        thresh_param=thresh_param
    )